-- pokemon table for postgresql
CREATE TABLE pokemon (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL
);

INSERT INTO pokemon (id, name, type) VALUES 
(1, 'Bulbasaur', 'Grass'),
(2, 'Ivysaur', 'Grass'),
(3, 'Venusaur', 'Grass'),
(4, 'Charmander', 'Fire'),
(5, 'Charmeleon', 'Fire'),
(6, 'Charizard', 'Fire'),
(7, 'Squirtle', 'Water'),
(8, 'Wartortle', 'Water'),
(9, 'Blastoise', 'Water'),
(10, 'Caterpie', 'Bug'),
(11, 'Metapod', 'Bug'),
(12, 'Butterfree', 'Bug'),
(13, 'Weedle', 'Bug'),
(14, 'Kakuna', 'Bug'),
(15, 'Beedrill', 'Bug'),
(16, 'Pidgey', 'Normal'),
(17, 'Pidgeotto', 'Normal'),
(18, 'Pidgeot', 'Normal'),
(19, 'Rattata', 'Normal'),
(20, 'Raticate', 'Normal'),
(21, 'Spearow', 'Normal'),
(22, 'Fearow', 'Normal'),
(23, 'Ekans', 'Poison'),
(24, 'Arbok', 'Poison'),
(25, 'Pikachu', 'Electric'),
(26, 'Raichu', 'Electric'),
(27, 'Sandshrew', 'Ground'),
(28, 'Sandslash', 'Ground'),
(29, 'Nidoran♀', 'Poison'),
(30, 'Nidorina', 'Poison'),
(31, 'Nidoqueen', 'Poison'),
(32, 'Nidoran♂', 'Poison'),
(33, 'Nidorino', 'Poison'),
(34, 'Nidoking', 'Poison'),
(35, 'Clefairy', 'Fairy'),
(36, 'Clefable', 'Fairy'),
(37, 'Vulpix', 'Fire'),
(38, 'Ninetales', 'Fire'),
(39, 'Jigglypuff', 'Normal'),
(40, 'Wigglytuff', 'Normal'),
(41, 'Zubat', 'Poison'),
(42, 'Golbat', 'Poison'),
(43, 'Oddish', 'GrassPoison'),
(44, 'Gloom', 'GrassPoison'),
(45, 'Vileplume', 'GrassPoison'),
(46, 'Paras', 'BugGrass'),
(47, 'Parasect', 'BugGrass'),
(48, 'Venonat', 'BugPoison'),
(49, 'Venomoth', 'BugPoison'),
(50, 'Diglett', 'Ground'),
(51, 'Dugtrio', 'Ground'),
(52, 'Meowth', 'Normal'),
(53, 'Persian', 'Normal'),
(54, 'Psyduck', 'Water'),
(55, 'Golduck', 'Water'),
(56, 'Mankey', 'Fighting'),
(57, 'Primeape', 'Fighting'),
(58, 'Growlithe', 'Fire'),
(59, 'Arcanine', 'Fire'),
(60, 'Poliwag', 'Water'),
(61, 'Poliwhirl', 'Water'),
(62, 'Poliwrath', 'WaterFighting'),
(63, 'Abra', 'Psychic'),
(64, 'Kadabra', 'Psychic'),
(65, 'Alakazam', 'Psychic'),
(66, 'Machop', 'Fighting'),
(67, 'Machoke', 'Fighting'),
(68, 'Machamp', 'Fighting'),
(69, 'Bellsprout', 'GrassPoison'),
(70, 'Weepinbell', 'GrassPoison'),
(71, 'Victreebel', 'GrassPoison'),
(72, 'Tentacool', 'WaterPoison'),
(73, 'Tentacruel', 'WaterPoison'),
(74, 'Geodude', 'RockGround'),
(75, 'Graveler', 'RockGround'),
(76, 'Golem', 'RockGround'),
(77, 'Ponyta', 'Fire'),
(78, 'Rapidash', 'Fire'),
(79, 'Slowpoke', 'WaterPsychic'),
(80, 'Slowbro', 'WaterPsychic'),
(81, 'Magnemite', 'ElectricSteel'),
(82, 'Magneton', 'ElectricSteel'),
(83, 'Farfetch''d', 'NormalFlying'),
(84, 'Doduo', 'NormalFlying'),
(85, 'Dodrio', 'NormalFlying'),
(86, 'Seel', 'Water'),
(87, 'Dewgong', 'WaterIce'),
(88, 'Grimer', 'Poison'),
(89, 'Muk', 'Poison'),
(90, 'Shellder', 'Water'),
(91, 'Cloyster', 'WaterIce'),
(92, 'Gastly', 'GhostPoison'),
(93, 'Haunter', 'GhostPoison'),
(94, 'Gengar', 'GhostPoison'),
(95, 'Onix', 'RockGround'),
(96, 'Drowzee', 'Psychic'),
(97, 'Hypno', 'Psychic'),
(98, 'Krabby', 'Water'),
(99, 'Kingler', 'Water'),
(100, 'Voltorb', 'Electric'),
(101, 'Electrode', 'Electric'),
(102, 'Exeggcute', 'GrassPsychic'),
(103, 'Exeggutor', 'GrassPsychic'),
(104, 'Cubone', 'Ground'),
(105, 'Marowak', 'Ground'),
(106, 'Hitmonlee', 'Fighting'),
(107, 'Hitmonchan', 'Fighting'),
(108, 'Lickitung', 'Normal'),
(109, 'Koffing', 'Poison'),
(110, 'Weezing', 'Poison'),
(111, 'Rhyhorn', 'GroundRock'),
(112, 'Rhydon', 'GroundRock'),
(113, 'Chansey', 'Normal'),
(114, 'Tangela', 'Grass'),
(115, 'Kangaskhan', 'Normal'),
(116, 'Horsea', 'Water'),
(117, 'Seadra', 'Water'),
(118, 'Goldeen', 'Water'),
(119, 'Seaking', 'Water'),
(120, 'Staryu', 'Water'),
(121, 'Starmie', 'WaterPsychic'),
(122, 'Mr. Mime', 'PsychicFairy'),
(123, 'Scyther', 'BugFlying'),
(124, 'Jynx', 'IcePsychic'),
(125, 'Electabuzz', 'Electric'),
(126, 'Magmar', 'Fire'),
(127, 'Pinsir', 'Bug'),
(128, 'Tauros', 'Normal'),
(129, 'Magikarp', 'Water'),
(130, 'Gyarados', 'WaterFlying'),
(131, 'Lapras', 'WaterIce'),
(132, 'Ditto', 'Normal'),
(133, 'Eevee', 'Normal'),
(134, 'Vaporeon', 'Water'),
(135, 'Jolteon', 'Electric'),
(136, 'Flareon', 'Fire'),
(137, 'Porygon', 'Normal'),
(138, 'Omanyte', 'RockWater'),
(139, 'Omastar', 'RockWater'),
(140, 'Kabuto', 'RockWater'),
(141, 'Kabutops', 'RockWater'),
(142, 'Aerodactyl', 'RockFlying'),
(143, 'Snorlax', 'Normal'),
(144, 'Articuno', 'IceFlying'),
(145, 'Zapdos', 'ElectricFlying'),
(146, 'Moltres', 'FireFlying'),
(147, 'Dratini', 'Dragon'),
(148, 'Dragonair', 'Dragon'),
(149, 'Dragonite', 'DragonFlying'),
(150, 'Mewtwo', 'Psychic'),
(151, 'Mew', 'Psychic'),
(152, 'Chikorita', 'Grass'),
(153, 'Bayleef', 'Grass'),
(154, 'Meganium', 'Grass'),
(155, 'Cyndaquil', 'Fire'),
(156, 'Quilava', 'Fire'),
(157, 'Typhlosion', 'Fire'),
(158, 'Totodile', 'Water'),
(159, 'Croconaw', 'Water'),
(160, 'Feraligatr', 'Water'),
(161, 'Sentret', 'Normal'),
(162, 'Furret', 'Normal'),
(163, 'Hoothoot', 'Normal'),
(164, 'Noctowl', 'Normal'),
(165, 'Ledyba', 'Bug'),
(166, 'Ledian', 'Bug'),
(167, 'Spinarak', 'Bug'),
(168, 'Ariados', 'Bug'),
(169, 'Crobat', 'Poison'),
(170, 'Chinchou', 'Water'),
(171, 'Lanturn', 'Water'),
(172, 'Pichu', 'Electric'),
(173, 'Cleffa', 'Fairy'),
(174, 'Igglybuff', 'Normal'),
(175, 'Togepi', 'Fairy'),
(176, 'Togetic', 'Fairy'),
(177, 'Natu', 'Psychic'),
(178, 'Xatu', 'Psychic'),
(179, 'Mareep', 'Electric'),
(180, 'Flaaffy', 'Electric'),
(181, 'Ampharos', 'Electric'),
(182, 'Bellossom', 'Grass'),
(183, 'Marill', 'Water'),
(184, 'Azumarill', 'Water'),
(185, 'Sudowoodo', 'Rock'),
(186, 'Politoed', 'Water'),
(187, 'Hoppip', 'Grass'),
(188, 'Skiploom', 'Grass'),
(189, 'Jumpluff', 'Grass'),
(190, 'Aipom', 'Normal'),
(191, 'Sunkern', 'Grass'),
(192, 'Sunflora', 'Grass'),
(193, 'Yanma', 'Bug'),
(194, 'Wooper', 'Water'),
(195, 'Quagsire', 'Water'),
(196, 'Espeon', 'Psychic'),
(197, 'Umbreon', 'Dark'),
(198, 'Murkrow', 'Dark'),
(199, 'Slowking', 'Water'),
(200, 'Misdreavus', 'Ghost'),
(201, 'Unown', 'Psychic'),
(202, 'Wobbuffet', 'Psychic'),
(203, 'Girafarig', 'Normal'),
(204, 'Pineco', 'Bug'),
(205, 'Forretress', 'Bug'),
(206, 'Dunsparce', 'Normal'),
(207, 'Gligar', 'Ground'),
(208, 'Steelix', 'Steel'),
(209, 'Snubbull', 'Fairy'),
(210, 'Granbull', 'Fairy'),
(211, 'Qwilfish', 'Water'),
(212, 'Scizor', 'Bug'),
(213, 'Shuckle', 'Bug'),
(214, 'Heracross', 'Bug'),
(215, 'Sneasel', 'Dark'),
(216, 'Teddiursa', 'Normal'),
(217, 'Ursaring', 'Normal'),
(218, 'Slugma', 'Fire'),
(219, 'Magcargo', 'Fire'),
(220, 'Swinub', 'Ice'),
(221, 'Piloswine', 'Ice'),
(222, 'Corsola', 'Water'),
(223, 'Remoraid', 'Water'),
(224, 'Octillery', 'Water'),
(225, 'Delibird', 'Ice'),
(226, 'Mantine', 'Water'),
(227, 'Skarmory', 'Steel'),
(228, 'Houndour', 'Dark'),
(229, 'Houndoom', 'Dark'),
(230, 'Kingdra', 'Water'),
(231, 'Phanpy', 'Ground'),
(232, 'Donphan', 'Ground'),
(233, 'Porygon2', 'Normal'),
(234, 'Stantler', 'Normal'),
(235, 'Smeargle', 'Normal'),
(236, 'Tyrogue', 'Fighting'),
(237, 'Hitmontop', 'Fighting'),
(238, 'Smoochum', 'Ice'),
(239, 'Elekid', 'Electric'),
(240, 'Magby', 'Fire'),
(241, 'Miltank', 'Normal'),
(242, 'Blissey', 'Normal'),
(243, 'Raikou', 'Electric'),
(244, 'Entei', 'Fire'),
(245, 'Suicune', 'Water'),
(246, 'Larvitar', 'Rock'),
(247, 'Pupitar', 'Rock'),
(248, 'Tyranitar', 'Rock'),
(249, 'Lugia', 'Psychic'),
(250, 'Ho-oh', 'Fire'),
(251, 'Celebi', 'Psychic'),
(252, 'Treecko', 'Grass'),
(253, 'Grovyle', 'Grass'),
(254, 'Sceptile', 'Grass'),
(255, 'Torchic', 'Fire'),
(256, 'Combusken', 'Fire'),
(257, 'Blaziken', 'Fire'),
(258, 'Mudkip', 'Water'),
(259, 'Marshtomp', 'Water'),
(260, 'Swampert', 'Water'),
(261, 'Poochyena', 'Dark'),
(262, 'Mightyena', 'Dark'),
(263, 'Zigzagoon', 'Normal'),
(264, 'Linoone', 'Normal'),
(265, 'Wurmple', 'Bug'),
(266, 'Silcoon', 'Bug'),
(267, 'Beautifly', 'Bug'),
(268, 'Cascoon', 'Bug'),
(269, 'Dustox', 'Bug'),
(270, 'Lotad', 'Water'),
(271, 'Lombre', 'Water'),
(272, 'Ludicolo', 'Water'),
(273, 'Seedot', 'Grass'),
(274, 'Nuzleaf', 'Grass'),
(275, 'Shiftry', 'Grass'),
(276, 'Taillow', 'Normal'),
(277, 'Swellow', 'Normal'),
(278, 'Wingull', 'Water'),
(279, 'Pelipper', 'Water'),
(280, 'Ralts', 'Psychic'),
(281, 'Kirlia', 'Psychic'),
(282, 'Gardevoir', 'Psychic'),
(283, 'Surskit', 'Bug'),
(284, 'Masquerain', 'Bug'),
(285, 'Shroomish', 'Grass'),
(286, 'Breloom', 'Grass'),
(287, 'Slakoth', 'Normal'),
(288, 'Vigoroth', 'Normal'),
(289, 'Slaking', 'Normal'),
(290, 'Nincada', 'Bug'),
(291, 'Ninjask', 'Bug'),
(292, 'Shedinja', 'Bug'),
(293, 'Whismur', 'Normal'),
(294, 'Loudred', 'Normal'),
(295, 'Exploud', 'Normal'),
(296, 'Makuhita', 'Fighting'),
(297, 'Hariyama', 'Fighting'),
(298, 'Azurill', 'Normal'),
(299, 'Nosepass', 'Rock'),
(300, 'Skitty', 'Normal'),
(301, 'Delcatty', 'Normal'),
(302, 'Sableye', 'Dark'),
(303, 'Mawile', 'Steel'),
(304, 'Aron', 'Steel'),
(305, 'Lairon', 'Steel'),
(306, 'Aggron', 'Steel'),
(307, 'Meditite', 'Fighting'),
(308, 'Medicham', 'Fighting'),
(309, 'Electrike', 'Electric'),
(310, 'Manectric', 'Electric'),
(311, 'Plusle', 'Electric'),
(312, 'Minun', 'Electric'),
(313, 'Volbeat', 'Bug'),
(314, 'Illumise', 'Bug'),
(315, 'Roselia', 'Grass'),
(316, 'Gulpin', 'Poison'),
(317, 'Swalot', 'Poison'),
(318, 'Carvanha', 'Water'),
(319, 'Sharpedo', 'Water'),
(320, 'Wailmer', 'Water'),
(321, 'Wailord', 'Water'),
(322, 'Numel', 'Fire'),
(323, 'Camerupt', 'Fire'),
(324, 'Torkoal', 'Fire'),
(325, 'Spoink', 'Psychic'),
(326, 'Grumpig', 'Psychic'),
(327, 'Spinda', 'Normal'),
(328, 'Trapinch', 'Ground'),
(329, 'Vibrava', 'Ground'),
(330, 'Flygon', 'Ground'),
(331, 'Cacnea', 'Grass'),
(332, 'Cacturne', 'Grass'),
(333, 'Swablu', 'Normal'),
(334, 'Altaria', 'Dragon'),
(335, 'Zangoose', 'Normal'),
(336, 'Seviper', 'Poison'),
(337, 'Lunatone', 'Rock'),
(338, 'Solrock', 'Rock'),
(339, 'Barboach', 'Water'),
(340, 'Whiscash', 'Water'),
(341, 'Corphish', 'Water'),
(342, 'Crawdaunt', 'Water'),
(343, 'Baltoy', 'Ground'),
(344, 'Claydol', 'Ground'),
(345, 'Lileep', 'Rock'),
(346, 'Cradily', 'Rock'),
(347, 'Anorith', 'Rock'),
(348, 'Armaldo', 'Rock'),
(349, 'Feebas', 'Water'),
(350, 'Milotic', 'Water'),
(351, 'Castform', 'Normal'),
(351, 'Castform', 'Sunny Form', 'Fire'),
(351, 'Castform', 'Rainy Form', 'Water'),
(351, 'Castform', 'Snowy Form', 'Ice'),
(352, 'Kecleon', 'Normal'),
(353, 'Shuppet', 'Ghost'),
(354, 'Banette', 'Ghost'),
(355, 'Duskull', 'Ghost'),
(356, 'Dusclops', 'Ghost'),
(357, 'Tropius', 'Grass'),
(358, 'Chimecho', 'Psychic'),
(359, 'Absol', 'Dark'),
(360, 'Wynaut', 'Psychic'),
(361, 'Snorunt', 'Ice'),
(362, 'Glalie', 'Ice'),
(363, 'Spheal', 'Ice'),
(364, 'Sealeo', 'Ice'),
(365, 'Walrein', 'Ice'),
(366, 'Clamperl', 'Water'),
(367, 'Huntail', 'Water'),
(368, 'Gorebyss', 'Water'),
(369, 'Relicanth', 'Water'),
(370, 'Luvdisc', 'Water'),
(371, 'Bagon', 'Dragon'),
(372, 'Shelgon', 'Dragon'),
(373, 'Salamence', 'Dragon'),
(374, 'Beldum', 'Steel'),
(375, 'Metang', 'Steel'),
(376, 'Metagross', 'Steel'),
(377, 'Regirock', 'Rock'),
(378, 'Regice', 'Ice'),
(379, 'Registeel', 'Steel'),
(380, 'Latias', 'Dragon'),
(381, 'Latios', 'Dragon'),
(382, 'Kyogre', 'Water'),
(383, 'Groudon', 'Ground'),
(384, 'Rayquaza', 'Dragon'),
(385, 'Jirachi', 'Steel'),
(386, 'Deoxys', 'Normal Forme', 'Psychic'),
(386, 'Deoxys', 'Attack Forme', 'Psychic'),
(386, 'Deoxys', 'Defense Forme', 'Psychic'),
(386, 'Deoxys', 'Speed Forme', 'Psychic'),
(387, 'Turtwig', 'Grass'),
(388, 'Grotle', 'Grass'),
(389, 'Torterra', 'Grass'),
(390, 'Chimchar', 'Fire'),
(391, 'Monferno', 'Fire'),
(392, 'Infernape', 'Fire'),
(393, 'Piplup', 'Water'),
(394, 'Prinplup', 'Water'),
(395, 'Empoleon', 'Water'),
(396, 'Starly', 'Normal'),
(397, 'Staravia', 'Normal'),
(398, 'Staraptor', 'Normal'),
(399, 'Bidoof', 'Normal'),
(400, 'Bibarel', 'Normal'),
(401, 'Kricketot', 'Bug'),
(402, 'Kricketune', 'Bug'),
(403, 'Shinx', 'Electric'),
(404, 'Luxio', 'Electric'),
(405, 'Luxray', 'Electric'),
(406, 'Budew', 'Grass'),
(407, 'Roserade', 'Grass'),
(408, 'Cranidos', 'Rock'),
(409, 'Rampardos', 'Rock'),
(410, 'Shieldon', 'Rock'),
(411, 'Bastiodon', 'Rock'),
(412, 'Burmy', 'Plant Cloak', 'Bug'),
(412, 'Burmy', 'Sandy Cloak', 'Bug'),
(412, 'Burmy', 'Trash Cloak', 'Bug'),
(413, 'Wormadam', 'Plant Cloak', 'Bug'),
(413, 'Wormadam', 'Sandy Cloak', 'Bug'),
(413, 'Wormadam', 'Trash Cloak', 'Bug'),
(414, 'Mothim', 'Bug'),
(415, 'Combee', 'Bug'),
(416, 'Vespiquen', 'Bug'),
(417, 'Pachirisu', 'Electric'),
(418, 'Buizel', 'Water'),
(419, 'Floatzel', 'Water'),
(420, 'Cherubi', 'Grass'),
(421, 'Cherrim', 'Grass'),
(422, 'Shellos', 'Water'),
(423, 'Gastrodon', 'Water'),
(424, 'Ambipom', 'Normal'),
(425, 'Drifloon', 'Ghost'),
(426, 'Drifblim', 'Ghost'),
(427, 'Buneary', 'Normal'),
(428, 'Lopunny', 'Normal'),
(429, 'Mismagius', 'Ghost'),
(430, 'Honchkrow', 'Dark'),
(431, 'Glameow', 'Normal'),
(432, 'Purugly', 'Normal'),
(433, 'Chingling', 'Psychic'),
(434, 'Stunky', 'Poison'),
(435, 'Skuntank', 'Poison'),
(436, 'Bronzor', 'Steel'),
(437, 'Bronzong', 'Steel'),
(438, 'Bonsly', 'Rock'),
(439, 'Mime Jr.', 'Psychic'),
(440, 'Happiny', 'Normal'),
(441, 'Chatot', 'Normal'),
(442, 'Spiritomb', 'Ghost'),
(443, 'Gible', 'Dragon'),
(444, 'Gabite', 'Dragon'),
(445, 'Garchomp', 'Dragon'),
(446, 'Munchlax', 'Normal'),
(447, 'Riolu', 'Fighting'),
(448, 'Lucario', 'Fighting'),
(449, 'Hippopotas', 'Ground'),
(450, 'Hippowdon', 'Ground'),
(451, 'Skorupi', 'Poison'),
(452, 'Drapion', 'Poison'),
(453, 'Croagunk', 'Poison'),
(454, 'Toxicroak', 'Poison'),
(455, 'Carnivine', 'Grass'),
(456, 'Finneon', 'Water'),
(457, 'Lumineon', 'Water'),
(458, 'Mantyke', 'Water'),
(459, 'Snover', 'Grass'),
(460, 'Abomasnow', 'Grass'),
(461, 'Weavile', 'Dark'),
(462, 'Magnezone', 'Electric'),
(463, 'Lickilicky', 'Normal'),
(464, 'Rhyperior', 'Ground'),
(465, 'Tangrowth', 'Grass'),
(466, 'Electivire', 'Electric'),
(467, 'Magmortar', 'Fire'),
(468, 'Togekiss', 'Fairy'),
(469, 'Yanmega', 'Bug'),
(470, 'Leafeon', 'Grass'),
(471, 'Glaceon', 'Ice'),
(472, 'Gliscor', 'Ground'),
(473, 'Mamoswine', 'Ice'),
(474, 'Porygon-Z', 'Normal'),
(475, 'Gallade', 'Psychic'),
(476, 'Probopass', 'Rock'),
(477, 'Dusknoir', 'Ghost'),
(478, 'Froslass', 'Ice'),
(479, 'Rotom', 'Electric'),
(479, 'Rotom', 'Heat Rotom', 'Electric'),
(479, 'Rotom', 'Wash Rotom', 'Electric'),
(479, 'Rotom', 'Frost Rotom', 'Electric'),
(479, 'Rotom', 'Fan Rotom', 'Electric'),
(479, 'Rotom', 'Mow Rotom', 'Electric'),
(480, 'Uxie', 'Psychic'),
(481, 'Mesprit', 'Psychic'),
(482, 'Azelf', 'Psychic'),
(483, 'Dialga', 'Steel'),
(484, 'Palkia', 'Water'),
(485, 'Heatran', 'Fire'),
(486, 'Regigigas', 'Normal'),
(487, 'Giratina', 'Altered Forme', 'Ghost'),
(487, 'Giratina', 'Origin Forme', 'Ghost'),
(488, 'Cresselia', 'Psychic'),
(489, 'Phione', 'Water'),
(490, 'Manaphy', 'Water'),
(491, 'Darkrai', 'Dark'),
(492, 'Shaymin', 'Land Forme', 'Grass'),
(492, 'Shaymin', 'Sky Forme', 'Grass'),
(493, 'Arceus', 'Normal'),
(494, 'Victini', 'Psychic'),
(495, 'Snivy', 'Grass'),
(496, 'Servine', 'Grass'),
(497, 'Serperior', 'Grass'),
(498, 'Tepig', 'Fire'),
(499, 'Pignite', 'Fire'),
(500, 'Emboar', 'Fire'),
(501, 'Oshawott', 'Water'),
(502, 'Dewott', 'Water'),
(503, 'Samurott', 'Water'),
(504, 'Patrat', 'Normal'),
(505, 'Watchog', 'Normal'),
(506, 'Lillipup', 'Normal'),
(507, 'Herdier', 'Normal'),
(508, 'Stoutland', 'Normal'),
(509, 'Purrloin', 'Dark'),
(510, 'Liepard', 'Dark'),
(511, 'Pansage', 'Grass'),
(512, 'Simisage', 'Grass'),
(513, 'Pansear', 'Fire'),
(514, 'Simisear', 'Fire'),
(515, 'Panpour', 'Water'),
(516, 'Simipour', 'Water'),
(517, 'Munna', 'Psychic'),
(518, 'Musharna', 'Psychic'),
(519, 'Pidove', 'Normal'),
(520, 'Tranquill', 'Normal'),
(521, 'Unfezant', 'Normal'),
(522, 'Blitzle', 'Electric'),
(523, 'Zebstrika', 'Electric'),
(524, 'Roggenrola', 'Rock'),
(525, 'Boldore', 'Rock'),
(526, 'Gigalith', 'Rock'),
(527, 'Woobat', 'Psychic'),
(528, 'Swoobat', 'Psychic'),
(529, 'Drilbur', 'Ground'),
(530, 'Excadrill', 'Ground'),
(531, 'Audino', 'Normal'),
(532, 'Timburr', 'Fighting'),
(533, 'Gurdurr', 'Fighting'),
(534, 'Conkeldurr', 'Fighting'),
(535, 'Tympole', 'Water'),
(536, 'Palpitoad', 'Water'),
(537, 'Seismitoad', 'Water'),
(538, 'Throh', 'Fighting'),
(539, 'Sawk', 'Fighting'),
(540, 'Sewaddle', 'Bug'),
(541, 'Swadloon', 'Bug'),
(542, 'Leavanny', 'Bug'),
(543, 'Venipede', 'Bug'),
(544, 'Whirlipede', 'Bug'),
(545, 'Scolipede', 'Bug'),
(546, 'Cottonee', 'Grass'),
(547, 'Whimsicott', 'Grass'),
(548, 'Petilil', 'Grass'),
(549, 'Lilligant', 'Grass'),
(550, 'Basculin', 'Red-Striped Form', 'Water'),
(550, 'Basculin', 'Blue-Striped Form', 'Water'),
(551, 'Sandile', 'Ground'),
(552, 'Krokorok', 'Ground'),
(553, 'Krookodile', 'Ground'),
(554, 'Darumaka', 'Fire'),
(555, 'Darmanitan', 'Standard Mode', 'Fire'),
(555, 'Darmanitan', 'Zen Mode', 'Fire'),
(556, 'Maractus', 'Grass'),
(557, 'Dwebble', 'Bug'),
(558, 'Crustle', 'Bug'),
(559, 'Scraggy', 'Dark'),
(560, 'Scrafty', 'Dark'),
(561, 'Sigilyph', 'Psychic'),
(562, 'Yamask', 'Ghost'),
(563, 'Cofagrigus', 'Ghost'),
(564, 'Tirtouga', 'Water'),
(565, 'Carracosta', 'Water'),
(566, 'Archen', 'Rock'),
(567, 'Archeops', 'Rock'),
(568, 'Trubbish', 'Poison'),
(569, 'Garbodor', 'Poison'),
(570, 'Zorua', 'Dark'),
(571, 'Zoroark', 'Dark'),
(572, 'Minccino', 'Normal'),
(573, 'Cinccino', 'Normal'),
(574, 'Gothita', 'Psychic'),
(575, 'Gothorita', 'Psychic'),
(576, 'Gothitelle', 'Psychic'),
(577, 'Solosis', 'Psychic'),
(578, 'Duosion', 'Psychic'),
(579, 'Reuniclus', 'Psychic'),
(580, 'Ducklett', 'Water'),
(581, 'Swanna', 'Water'),
(582, 'Vanillite', 'Ice'),
(583, 'Vanillish', 'Ice'),
(584, 'Vanilluxe', 'Ice'),
(585, 'Deerling', 'Normal'),
(586, 'Sawsbuck', 'Normal'),
(587, 'Emolga', 'Electric'),
(588, 'Karrablast', 'Bug'),
(589, 'Escavalier', 'Bug'),
(590, 'Foongus', 'Grass'),
(591, 'Amoonguss', 'Grass'),
(592, 'Frillish', 'Water'),
(593, 'Jellicent', 'Water'),
(594, 'Alomomola', 'Water'),
(595, 'Joltik', 'Bug'),
(596, 'Galvantula', 'Bug'),
(597, 'Ferroseed', 'Grass'),
(598, 'Ferrothorn', 'Grass'),
(599, 'Klink', 'Steel'),
(600, 'Klang', 'Steel'),
(601, 'Klinklang', 'Steel'),
(602, 'Tynamo', 'Electric'),
(603, 'Eelektrik', 'Electric'),
(604, 'Eelektross', 'Electric'),
(605, 'Elgyem', 'Psychic'),
(606, 'Beheeyem', 'Psychic'),
(607, 'Litwick', 'Ghost'),
(608, 'Lampent', 'Ghost'),
(609, 'Chandelure', 'Ghost'),
(610, 'Axew', 'Dragon'),
(611, 'Fraxure', 'Dragon'),
(612, 'Haxorus', 'Dragon'),
(613, 'Cubchoo', 'Ice'),
(614, 'Beartic', 'Ice'),
(615, 'Cryogonal', 'Ice'),
(616, 'Shelmet', 'Bug'),
(617, 'Accelgor', 'Bug'),
(618, 'Stunfisk', 'Ground'),
(619, 'Mienfoo', 'Fighting'),
(620, 'Mienshao', 'Fighting'),
(621, 'Druddigon', 'Dragon'),
(622, 'Golett', 'Ground'),
(623, 'Golurk', 'Ground'),
(624, 'Pawniard', 'Dark'),
(625, 'Bisharp', 'Dark'),
(626, 'Bouffalant', 'Normal'),
(627, 'Rufflet', 'Normal'),
(628, 'Braviary', 'Normal'),
(629, 'Vullaby', 'Dark'),
(630, 'Mandibuzz', 'Dark'),
(631, 'Heatmor', 'Fire'),
(632, 'Durant', 'Bug'),
(633, 'Deino', 'Dark'),
(634, 'Zweilous', 'Dark'),
(635, 'Hydreigon', 'Dark'),
(636, 'Larvesta', 'Bug'),
(637, 'Volcarona', 'Bug'),
(638, 'Cobalion', 'Steel'),
(639, 'Terrakion', 'Rock'),
(640, 'Virizion', 'Grass'),
(641, 'Tornadus', 'Incarnate Forme', 'Flying'),
(641, 'Tornadus', 'Therian Forme', 'Flying'),
(642, 'Thundurus', 'Incarnate Forme', 'Electric'),
(642, 'Thundurus', 'Therian Forme', 'Electric'),
(643, 'Reshiram', 'Dragon'),
(644, 'Zekrom', 'Dragon'),
(645, 'Landorus', 'Incarnate Forme', 'Ground'),
(645, 'Landorus', 'Therian Forme', 'Ground'),
(646, 'Kyurem', 'Dragon'),
(646, 'Kyurem', 'White Kyurem', 'Dragon'),
(646, 'Kyurem', 'Black Kyurem', 'Dragon'),
(647, 'Keldeo', 'Ordinary Form', 'Water'),
(647, 'Keldeo', 'Resolute Form', 'Water'),
(648, 'Meloetta', 'Aria Forme', 'Normal'),
(648, 'Meloetta', 'Pirouette Forme', 'Normal'),
(649, 'Genesect', 'Bug'),
(3, 'Venusaur', 'Mega Venusaur', 'Grass'),
(6, 'Charizard', 'Mega Charizard X', 'Fire'),
(6, 'Charizard', 'Mega Charizard Y', 'Fire'),
(9, 'Blastoise', 'Mega Blastoise', 'Water'),
(15, 'Beedrill', 'Mega Beedrill', 'Bug'),
(18, 'Pidgeot', 'Mega Pidgeot', 'Normal'),
(65, 'Alakazam', 'Mega Alakazam', 'Psychic'),
(80, 'Slowbro', 'Mega Slowbro', 'Water'),
(94, 'Gengar', 'Mega Gengar', 'Ghost'),
(115, 'Kangaskhan', 'Mega Kangaskhan', 'Normal'),
(127, 'Pinsir', 'Mega Pinsir', 'Bug'),
(130, 'Gyarados', 'Mega Gyarados', 'Water'),
(142, 'Aerodactyl', 'Mega Aerodactyl', 'Rock'),
(150, 'Mewtwo', 'Mega Mewtwo X', 'Psychic'),
(150, 'Mewtwo', 'Mega Mewtwo Y', 'Psychic'),
(181, 'Ampharos', 'Mega Ampharos', 'Electric'),
(208, 'Steelix', 'Mega Steelix', 'Steel'),
(212, 'Scizor', 'Mega Scizor', 'Bug'),
(214, 'Heracross', 'Mega Heracross', 'Bug'),
(229, 'Houndoom', 'Mega Houndoom', 'Dark'),
(248, 'Tyranitar', 'Mega Tyranitar', 'Rock'),
(254, 'Sceptile', 'Mega Sceptile', 'Grass'),
(257, 'Blaziken', 'Mega Blaziken', 'Fire'),
(260, 'Swampert', 'Mega Swampert', 'Water'),
(282, 'Gardevoir', 'Mega Gardevoir', 'Psychic'),
(302, 'Sableye', 'Mega Sableye', 'Dark'),
(303, 'Mawile', 'Mega Mawile', 'Steel'),
(306, 'Aggron', 'Mega Aggron', 'Steel'),
(308, 'Medicham', 'Mega Medicham', 'Fighting'),
(310, 'Manectric', 'Mega Manectric', 'Electric'),
(319, 'Sharpedo', 'Mega Sharpedo', 'Water'),
(323, 'Camerupt', 'Mega Camerupt', 'Fire'),
(334, 'Altaria', 'Mega Altaria', 'Dragon'),
(354, 'Banette', 'Mega Banette', 'Ghost'),
(359, 'Absol', 'Mega Absol', 'Dark'),
(362, 'Glalie', 'Mega Glalie', 'Ice'),
(373, 'Salamence', 'Mega Salamence', 'Dragon'),
(376, 'Metagross', 'Mega Metagross', 'Steel'),
(380, 'Latias', 'Mega Latias', 'Dragon'),
(381, 'Latios', 'Mega Latios', 'Dragon'),
(382, 'Kyogre', 'Primal Kyogre', 'Water'),
(383, 'Groudon', 'Primal Groudon', 'Ground'),
(384, 'Rayquaza', 'Mega Rayquaza', 'Dragon'),
(428, 'Lopunny', 'Mega Lopunny', 'Normal'),
(445, 'Garchomp', 'Mega Garchomp', 'Dragon'),
(448, 'Lucario', 'Mega Lucario', 'Fighting'),
(460, 'Abomasnow', 'Mega Abomasnow', 'Grass'),
(475, 'Gallade', 'Mega Gallade', 'Psychic'),
(531, 'Audino', 'Mega Audino', 'Normal'),
(650, 'Chespin', 'Grass'),
(651, 'Quilladin', 'Grass'),
(652, 'Chesnaught', 'Grass'),
(653, 'Fennekin', 'Fire'),
(654, 'Braixen', 'Fire'),
(655, 'Delphox', 'Fire'),
(656, 'Froakie', 'Water'),
(657, 'Frogadier', 'Water'),
(658, 'Greninja', 'Water'),
(659, 'Bunnelby', 'Normal'),
(660, 'Diggersby', 'Normal'),
(661, 'Fletchling', 'Normal'),
(662, 'Fletchinder', 'Fire'),
(663, 'Talonflame', 'Fire'),
(664, 'Scatterbug', 'Bug'),
(665, 'Spewpa', 'Bug'),
(666, 'Vivillon', 'Bug'),
(667, 'Litleo', 'Fire'),
(668, 'Pyroar', 'Fire'),
(669, 'Flabébé', 'Fairy'),
(670, 'Floette', 'Fairy'),
(671, 'Florges', 'Fairy'),
(672, 'Skiddo', 'Grass'),
(673, 'Gogoat', 'Grass'),
(674, 'Pancham', 'Fighting'),
(675, 'Pangoro', 'Fighting'),
(676, 'Furfrou', 'Normal'),
(677, 'Espurr', 'Psychic'),
(678, 'Meowstic', 'Male', 'Psychic'),
(678, 'Meowstic', 'Female', 'Psychic'),
(679, 'Honedge', 'Steel'),
(680, 'Doublade', 'Steel'),
(681, 'Aegislash', 'Shield Forme', 'Steel'),
(681, 'Aegislash', 'Blade Forme', 'Steel'),
(682, 'Spritzee', 'Fairy'),
(683, 'Aromatisse', 'Fairy'),
(684, 'Swirlix', 'Fairy'),
(685, 'Slurpuff', 'Fairy'),
(686, 'Inkay', 'Dark'),
(687, 'Malamar', 'Dark'),
(688, 'Binacle', 'Rock'),
(689, 'Barbaracle', 'Rock'),
(690, 'Skrelp', 'Poison'),
(691, 'Dragalge', 'Poison'),
(692, 'Clauncher', 'Water'),
(693, 'Clawitzer', 'Water'),
(694, 'Helioptile', 'Electric'),
(695, 'Heliolisk', 'Electric'),
(696, 'Tyrunt', 'Rock'),
(697, 'Tyrantrum', 'Rock'),
(698, 'Amaura', 'Rock'),
(699, 'Aurorus', 'Rock'),
(700, 'Sylveon', 'Fairy'),
(701, 'Hawlucha', 'Fighting'),
(702, 'Dedenne', 'Electric'),
(703, 'Carbink', 'Rock'),
(704, 'Goomy', 'Dragon'),
(705, 'Sliggoo', 'Dragon'),
(706, 'Goodra', 'Dragon'),
(707, 'Klefki', 'Steel'),
(708, 'Phantump', 'Ghost'),
(709, 'Trevenant', 'Ghost'),
(710, 'Pumpkaboo', 'Average Size', 'Ghost'),
(710, 'Pumpkaboo', 'Small Size', 'Ghost'),
(710, 'Pumpkaboo', 'Large Size', 'Ghost'),
(710, 'Pumpkaboo', 'Super Size', 'Ghost'),
(711, 'Gourgeist', 'Average Size', 'Ghost'),
(711, 'Gourgeist', 'Small Size', 'Ghost'),
(711, 'Gourgeist', 'Large Size', 'Ghost'),
(711, 'Gourgeist', 'Super Size', 'Ghost'),
(712, 'Bergmite', 'Ice'),
(713, 'Avalugg', 'Ice'),
(714, 'Noibat', 'Flying'),
(715, 'Noivern', 'Flying'),
(716, 'Xerneas', 'Fairy'),
(717, 'Yveltal', 'Dark'),
(718, 'Zygarde50% Forme', 'Dragon'),
(719, 'Diancie', 'Rock'),
(719, 'Diancie', 'Mega Diancie', 'Rock'),
(720, 'Hoopa', 'Hoopa Confined', 'Psychic'),
(720, 'Hoopa', 'Hoopa Unbound', 'Psychic'),
(721, 'Volcanion', 'Fire'),
(19, 'Rattata', 'Alolan Rattata', 'Dark'),
(20, 'Raticate', 'Alolan Raticate', 'Dark'),
(25, 'Pikachu', 'Partner Pikachu', 'Electric'),
(26, 'Raichu', 'Alolan Raichu', 'Electric'),
(27, 'Sandshrew', 'Alolan Sandshrew', 'Ice'),
(28, 'Sandslash', 'Alolan Sandslash', 'Ice'),
(37, 'Vulpix', 'Alolan Vulpix', 'Ice'),
(38, 'Ninetales', 'Alolan Ninetales', 'Ice'),
(50, 'Diglett', 'Alolan Diglett', 'Ground'),
(51, 'Dugtrio', 'Alolan Dugtrio', 'Ground'),
(52, 'Meowth', 'Alolan Meowth', 'Dark'),
(53, 'Persian', 'Alolan Persian', 'Dark'),
(74, 'Geodude', 'Alolan Geodude', 'Rock'),
(75, 'Graveler', 'Alolan Graveler', 'Rock'),
(76, 'Golem', 'Alolan Golem', 'Rock'),
(88, 'Grimer', 'Alolan Grimer', 'Poison'),
(89, 'Muk', 'Alolan Muk', 'Poison'),
(103, 'Exeggutor', 'Alolan Exeggutor', 'Grass'),
(105, 'Marowak', 'Alolan Marowak', 'Fire'),
(133, 'Eevee', 'Partner Eevee', 'Normal'),
(658, 'Greninja', 'Ash-Greninja', 'Water'),
(718, 'Zygarde10% Forme', 'Dragon'),
(718, 'Zygarde', 'Complete Forme', 'Dragon'),
(722, 'Rowlet', 'Grass'),
(723, 'Dartrix', 'Grass'),
(724, 'Decidueye', 'Grass'),
(725, 'Litten', 'Fire'),
(726, 'Torracat', 'Fire'),
(727, 'Incineroar', 'Fire'),
(728, 'Popplio', 'Water'),
(729, 'Brionne', 'Water'),
(730, 'Primarina', 'Water'),
(731, 'Pikipek', 'Normal'),
(732, 'Trumbeak', 'Normal'),
(733, 'Toucannon', 'Normal'),
(734, 'Yungoos', 'Normal'),
(735, 'Gumshoos', 'Normal'),
(736, 'Grubbin', 'Bug'),
(737, 'Charjabug', 'Bug'),
(738, 'Vikavolt', 'Bug'),
(739, 'Crabrawler', 'Fighting'),
(740, 'Crabominable', 'Fighting'),
(741, 'Oricorio', 'Baile Style', 'Fire'),
(741, 'Oricorio', 'Pom-Pom Style', 'Electric'),
(741, 'Oricorio', 'Pa'u Style', 'Psychic'),
(741, 'Oricorio', 'Sensu Style', 'Ghost'),
(742, 'Cutiefly', 'Bug'),
(743, 'Ribombee', 'Bug'),
(744, 'Rockruff', 'Rock'),
(744, 'Rockruff', 'Own Tempo Rockruff', 'Rock'),
(745, 'Lycanroc', 'Midday Form', 'Rock'),
(745, 'Lycanroc', 'Midnight Form', 'Rock'),
(745, 'Lycanroc', 'Dusk Form', 'Rock'),
(746, 'Wishiwashi', 'Solo Form', 'Water'),
(746, 'Wishiwashi', 'School Form', 'Water'),
(747, 'Mareanie', 'Poison'),
(748, 'Toxapex', 'Poison'),
(749, 'Mudbray', 'Ground'),
(750, 'Mudsdale', 'Ground'),
(751, 'Dewpider', 'Water'),
(752, 'Araquanid', 'Water'),
(753, 'Fomantis', 'Grass'),
(754, 'Lurantis', 'Grass'),
(755, 'Morelull', 'Grass'),
(756, 'Shiinotic', 'Grass'),
(757, 'Salandit', 'Poison'),
(758, 'Salazzle', 'Poison'),
(759, 'Stufful', 'Normal'),
(760, 'Bewear', 'Normal'),
(761, 'Bounsweet', 'Grass'),
(762, 'Steenee', 'Grass'),
(763, 'Tsareena', 'Grass'),
(764, 'Comfey', 'Fairy'),
(765, 'Oranguru', 'Normal'),
(766, 'Passimian', 'Fighting'),
(767, 'Wimpod', 'Bug'),
(768, 'Golisopod', 'Bug'),
(769, 'Sandygast', 'Ghost'),
(770, 'Palossand', 'Ghost'),
(771, 'Pyukumuku', 'Water'),
(772, 'Type: Null', 'Normal'),
(773, 'Silvally', 'Normal'),
(774, 'Minior', 'Meteor Form', 'Rock'),
(774, 'Minior', 'Core Form', 'Rock'),
(775, 'Komala', 'Normal'),
(776, 'Turtonator', 'Fire'),
(777, 'Togedemaru', 'Electric'),
(778, 'Mimikyu', 'Ghost'),
(779, 'Bruxish', 'Water'),
(780, 'Drampa', 'Normal'),
(781, 'Dhelmise', 'Ghost'),
(782, 'Jangmo-o', 'Dragon'),
(783, 'Hakamo-o', 'Dragon'),
(784, 'Kommo-o', 'Dragon'),
(785, 'Tapu Koko', 'Electric'),
(786, 'Tapu Lele', 'Psychic'),
(787, 'Tapu Bulu', 'Grass'),
(788, 'Tapu Fini', 'Water'),
(789, 'Cosmog', 'Psychic'),
(790, 'Cosmoem', 'Psychic'),
(791, 'Solgaleo', 'Psychic'),
(792, 'Lunala', 'Psychic'),
(793, 'Nihilego', 'Rock'),
(794, 'Buzzwole', 'Bug'),
(795, 'Pheromosa', 'Bug'),
(796, 'Xurkitree', 'Electric'),
(797, 'Celesteela', 'Steel'),
(798, 'Kartana', 'Grass'),
(799, 'Guzzlord', 'Dark'),
(800, 'Necrozma', 'Psychic'),
(800, 'Necrozma', 'Dusk Mane Necrozma', 'Psychic'),
(800, 'Necrozma', 'Dawn Wings Necrozma', 'Psychic'),
(800, 'Necrozma', 'Ultra Necrozma', 'Psychic'),
(801, 'Magearna', 'Steel'),
(802, 'Marshadow', 'Fighting'),
(803, 'Poipole', 'Poison'),
(804, 'Naganadel', 'Poison'),
(805, 'Stakataka', 'Rock'),
(806, 'Blacephalon', 'Fire'),
(807, 'Zeraora', 'Electric'),
(808, 'Meltan', 'Steel'),
(809, 'Melmetal', 'Steel'),
(52, 'Meowth', 'Galarian Meowth', 'Steel'),
(58, 'Growlithe', 'Hisuian Growlithe', 'Fire'),
(59, 'Arcanine', 'Hisuian Arcanine', 'Fire'),
(77, 'Ponyta', 'Galarian Ponyta', 'Psychic'),
(78, 'Rapidash', 'Galarian Rapidash', 'Psychic'),
(79, 'Slowpoke', 'Galarian Slowpoke', 'Psychic'),
(80, 'Slowbro', 'Galarian Slowbro', 'Poison'),
(83, 'Farfetch'd', 'Galarian Farfetch'd', 'Fighting'),
(100, 'Voltorb', 'Hisuian Voltorb', 'Electric'),
(101, 'Electrode', 'Hisuian Electrode', 'Electric'),
(110, 'Weezing', 'Galarian Weezing', 'Poison'),
(122, 'Mr. Mime', 'Galarian Mr. Mime', 'Ice'),
(144, 'Articuno', 'Galarian Articuno', 'Psychic'),
(145, 'Zapdos', 'Galarian Zapdos', 'Fighting'),
(146, 'Moltres', 'Galarian Moltres', 'Dark'),
(157, 'Typhlosion', 'Hisuian Typhlosion', 'Fire'),
(199, 'Slowking', 'Galarian Slowking', 'Poison'),
(211, 'Qwilfish', 'Hisuian Qwilfish', 'Dark'),
(215, 'Sneasel', 'Hisuian Sneasel', 'Fighting'),
(222, 'Corsola', 'Galarian Corsola', 'Ghost'),
(263, 'Zigzagoon', 'Galarian Zigzagoon', 'Dark'),
(264, 'Linoone', 'Galarian Linoone', 'Dark'),
(483, 'Dialga', 'Origin Forme', 'Steel'),
(484, 'Palkia', 'Origin Forme', 'Water'),
(503, 'Samurott', 'Hisuian Samurott', 'Water'),
(549, 'Lilligant', 'Hisuian Lilligant', 'Grass'),
(550, 'Basculin', 'White-Striped Form', 'Water'),
(554, 'Darumaka', 'Galarian Darumaka', 'Ice'),
(555, 'Darmanitan', 'Galarian Standard Mode', 'Ice'),
(555, 'Darmanitan', 'Galarian Zen Mode', 'Ice'),
(562, 'Yamask', 'Galarian Yamask', 'Ground'),
(570, 'Zorua', 'Hisuian Zorua', 'Normal'),
(571, 'Zoroark', 'Hisuian Zoroark', 'Normal'),
(618, 'Stunfisk', 'Galarian Stunfisk', 'Ground'),
(628, 'Braviary', 'Hisuian Braviary', 'Psychic'),
(705, 'Sliggoo', 'Hisuian Sliggoo', 'Steel'),
(706, 'Goodra', 'Hisuian Goodra', 'Steel'),
(713, 'Avalugg', 'Hisuian Avalugg', 'Ice'),
(724, 'Decidueye', 'Hisuian Decidueye', 'Grass'),
(810, 'Grookey', 'Grass'),
(811, 'Thwackey', 'Grass'),
(812, 'Rillaboom', 'Grass'),
(813, 'Scorbunny', 'Fire'),
(814, 'Raboot', 'Fire'),
(815, 'Cinderace', 'Fire'),
(816, 'Sobble', 'Water'),
(817, 'Drizzile', 'Water'),
(818, 'Inteleon', 'Water'),
(819, 'Skwovet', 'Normal'),
(820, 'Greedent', 'Normal'),
(821, 'Rookidee', 'Flying'),
(822, 'Corvisquire', 'Flying'),
(823, 'Corviknight', 'Flying'),
(824, 'Blipbug', 'Bug'),
(825, 'Dottler', 'Bug'),
(826, 'Orbeetle', 'Bug'),
(827, 'Nickit', 'Dark'),
(828, 'Thievul', 'Dark'),
(829, 'Gossifleur', 'Grass'),
(830, 'Eldegoss', 'Grass'),
(831, 'Wooloo', 'Normal'),
(832, 'Dubwool', 'Normal'),
(833, 'Chewtle', 'Water'),
(834, 'Drednaw', 'Water'),
(835, 'Yamper', 'Electric'),
(836, 'Boltund', 'Electric'),
(837, 'Rolycoly', 'Rock'),
(838, 'Carkol', 'Rock'),
(839, 'Coalossal', 'Rock'),
(840, 'Applin', 'Grass'),
(841, 'Flapple', 'Grass'),
(842, 'Appletun', 'Grass'),
(843, 'Silicobra', 'Ground'),
(844, 'Sandaconda', 'Ground'),
(845, 'Cramorant', 'Flying'),
(846, 'Arrokuda', 'Water'),
(847, 'Barraskewda', 'Water'),
(848, 'Toxel', 'Electric'),
(849, 'Toxtricity', 'Amped Form', 'Electric'),
(849, 'Toxtricity', 'Low Key Form', 'Electric'),
(850, 'Sizzlipede', 'Fire'),
(851, 'Centiskorch', 'Fire'),
(852, 'Clobbopus', 'Fighting'),
(853, 'Grapploct', 'Fighting'),
(854, 'Sinistea', 'Ghost'),
(855, 'Polteageist', 'Ghost'),
(856, 'Hatenna', 'Psychic'),
(857, 'Hattrem', 'Psychic'),
(858, 'Hatterene', 'Psychic'),
(859, 'Impidimp', 'Dark'),
(860, 'Morgrem', 'Dark'),
(861, 'Grimmsnarl', 'Dark'),
(862, 'Obstagoon', 'Dark'),
(863, 'Perrserker', 'Steel'),
(864, 'Cursola', 'Ghost'),
(865, 'Sirfetch'd', 'Fighting'),
(866, 'Mr. Rime', 'Ice'),
(867, 'Runerigus', 'Ground'),
(868, 'Milcery', 'Fairy'),
(869, 'Alcremie', 'Fairy'),
(870, 'Falinks', 'Fighting'),
(871, 'Pincurchin', 'Electric'),
(872, 'Snom', 'Ice'),
(873, 'Frosmoth', 'Ice'),
(874, 'Stonjourner', 'Rock'),
(875, 'Eiscue', 'Ice Face', 'Ice'),
(875, 'Eiscue', 'Noice Face', 'Ice'),
(876, 'Indeedee', 'Male', 'Psychic'),
(876, 'Indeedee', 'Female', 'Psychic'),
(877, 'Morpeko', 'Full Belly Mode', 'Electric'),
(877, 'Morpeko', 'Hangry Mode', 'Electric'),
(878, 'Cufant', 'Steel'),
(879, 'Copperajah', 'Steel'),
(880, 'Dracozolt', 'Electric'),
(881, 'Arctozolt', 'Electric'),
(882, 'Dracovish', 'Water'),
(883, 'Arctovish', 'Water'),
(884, 'Duraludon', 'Steel'),
(885, 'Dreepy', 'Dragon'),
(886, 'Drakloak', 'Dragon'),
(887, 'Dragapult', 'Dragon'),
(888, 'Zacian', 'Hero of Many Battles', 'Fairy'),
(888, 'Zacian', 'Crowned Sword', 'Fairy'),
(889, 'Zamazenta', 'Hero of Many Battles', 'Fighting'),
(889, 'Zamazenta', 'Crowned Shield', 'Fighting'),
(890, 'Eternatus', 'Poison'),
(890, 'Eternatus', 'Eternamax', 'Poison'),
(891, 'Kubfu', 'Fighting'),
(892, 'Urshifu', 'Single Strike Style', 'Fighting'),
(892, 'Urshifu', 'Rapid Strike Style', 'Fighting'),
(893, 'Zarude', 'Dark'),
(894, 'Regieleki', 'Electric'),
(895, 'Regidrago', 'Dragon'),
(896, 'Glastrier', 'Ice'),
(897, 'Spectrier', 'Ghost'),
(898, 'Calyrex', 'Psychic'),
(898, 'Calyrex', 'Ice Rider', 'Psychic'),
(898, 'Calyrex', 'Shadow Rider', 'Psychic'),
(899, 'Wyrdeer', 'Normal'),
(900, 'Kleavor', 'Bug'),
(901, 'Ursaluna', 'Ground'),
(902, 'Basculegion', 'Male', 'Water'),
(902, 'Basculegion', 'Female', 'Water'),
(903, 'Sneasler', 'Fighting'),
(904, 'Overqwil', 'Dark'),
(905, 'Enamorus', 'Incarnate Forme', 'Fairy'),
(905, 'Enamorus', 'Therian Forme', 'Fairy'),
(128, 'Tauros', 'Combat Breed', 'Fighting'),
(128, 'Tauros', 'Blaze Breed', 'Fighting'),
(128, 'Tauros', 'Aqua Breed', 'Fighting'),
(194, 'Wooper', 'Paldean Wooper', 'Poison'),
(906, 'Sprigatito', 'Grass'),
(907, 'Floragato', 'Grass'),
(908, 'Meowscarada', 'Grass'),
(909, 'Fuecoco', 'Fire'),
(910, 'Crocalor', 'Fire'),
(911, 'Skeledirge', 'Fire'),
(912, 'Quaxly', 'Water'),
(913, 'Quaxwell', 'Water'),
(914, 'Quaquaval', 'Water'),
(915, 'Lechonk', 'Normal'),
(916, 'Oinkologne', 'Male', 'Normal'),
(916, 'Oinkologne', 'Female', 'Normal'),
(917, 'Tarountula', 'Bug'),
(918, 'Spidops', 'Bug'),
(919, 'Nymble', 'Bug'),
(920, 'Lokix', 'Bug'),
(921, 'Pawmi', 'Electric'),
(922, 'Pawmo', 'Electric'),
(923, 'Pawmot', 'Electric'),
(924, 'Tandemaus', 'Normal'),
(925, 'Maushold', 'Family of Four', 'Normal'),
(925, 'Maushold', 'Family of Three', 'Normal'),
(926, 'Fidough', 'Fairy'),
(927, 'Dachsbun', 'Fairy'),
(928, 'Smoliv', 'Grass'),
(929, 'Dolliv', 'Grass'),
(930, 'Arboliva', 'Grass'),
(931, 'Squawkabilly', 'Green Plumage', 'Normal'),
(931, 'Squawkabilly', 'Blue Plumage', 'Normal'),
(931, 'Squawkabilly', 'Yellow Plumage', 'Normal'),
(931, 'Squawkabilly', 'White Plumage', 'Normal'),
(932, 'Nacli', 'Rock'),
(933, 'Naclstack', 'Rock'),
(934, 'Garganacl', 'Rock'),
(935, 'Charcadet', 'Fire'),
(936, 'Armarouge', 'Fire'),
(937, 'Ceruledge', 'Fire'),
(938, 'Tadbulb', 'Electric'),
(939, 'Bellibolt', 'Electric'),
(940, 'Wattrel', 'Electric'),
(941, 'Kilowattrel', 'Electric'),
(942, 'Maschiff', 'Dark'),
(943, 'Mabosstiff', 'Dark'),
(944, 'Shroodle', 'Poison'),
(945, 'Grafaiai', 'Poison'),
(946, 'Bramblin', 'Grass'),
(947, 'Brambleghast', 'Grass'),
(948, 'Toedscool', 'Ground'),
(949, 'Toedscruel', 'Ground'),
(950, 'Klawf', 'Rock'),
(951, 'Capsakid', 'Grass'),
(952, 'Scovillain', 'Grass'),
(953, 'Rellor', 'Bug'),
(954, 'Rabsca', 'Bug'),
(955, 'Flittle', 'Psychic'),
(956, 'Espathra', 'Psychic'),
(957, 'Tinkatink', 'Fairy'),
(958, 'Tinkatuff', 'Fairy'),
(959, 'Tinkaton', 'Fairy'),
(960, 'Wiglett', 'Water'),
(961, 'Wugtrio', 'Water'),
(962, 'Bombirdier', 'Flying'),
(963, 'Finizen', 'Water'),
(964, 'Palafin', 'Zero Form', 'Water'),
(964, 'Palafin', 'Hero Form', 'Water'),
(965, 'Varoom', 'Steel'),
(966, 'Revavroom', 'Steel'),
(967, 'Cyclizar', 'Dragon'),
(968, 'Orthworm', 'Steel'),
(969, 'Glimmet', 'Rock'),
(970, 'Glimmora', 'Rock'),
(971, 'Greavard', 'Ghost'),
(972, 'Houndstone', 'Ghost'),
(973, 'Flamigo', 'Flying'),
(974, 'Cetoddle', 'Ice'),
(975, 'Cetitan', 'Ice'),
(976, 'Veluza', 'Water'),
(977, 'Dondozo', 'Water'),
(978, 'Tatsugiri', 'Curly Form', 'Dragon'),
(978, 'Tatsugiri', 'Droopy Form', 'Dragon'),
(978, 'Tatsugiri', 'Stretchy Form', 'Dragon'),
(979, 'Annihilape', 'Fighting'),
(980, 'Clodsire', 'Poison'),
(981, 'Farigiraf', 'Normal'),
(982, 'Dudunsparce', 'Two-Segment Form', 'Normal'),
(982, 'Dudunsparce', 'Three-Segment Form', 'Normal'),
(983, 'Kingambit', 'Dark'),
(984, 'Great Tusk', 'Ground'),
(985, 'Scream Tail', 'Fairy'),
(986, 'Brute Bonnet', 'Grass'),
(987, 'Flutter Mane', 'Ghost'),
(988, 'Slither Wing', 'Bug'),
(989, 'Sandy Shocks', 'Electric'),
(990, 'Iron Treads', 'Ground'),
(991, 'Iron Bundle', 'Ice'),
(992, 'Iron Hands', 'Fighting'),
(993, 'Iron Jugulis', 'Dark'),
(994, 'Iron Moth', 'Fire'),
(995, 'Iron Thorns', 'Rock'),
(996, 'Frigibax', 'Dragon'),
(997, 'Arctibax', 'Dragon'),
(998, 'Baxcalibur', 'Dragon'),
(999, 'Gimmighoul', 'Chest Form', 'Ghost'),
(999, 'Gimmighoul', 'Roaming Form', 'Ghost'),
(1000, 'Gholdengo', 'Steel'),
(1001, 'Wo-Chien', 'Dark'),
(1002, 'Chien-Pao', 'Dark'),
(1003, 'Ting-Lu', 'Dark'),
(1004, 'Chi-Yu', 'Dark'),
(1005, 'Roaring Moon', 'Dragon'),
(1006, 'Iron Valiant', 'Fairy'),
(1007, 'Koraidon', 'Fighting'),
(1008, 'Miraidon', 'Electric'),
(1009, 'Walking Wake', 'Water'),
(1010, 'Iron Leaves', 'Grass'),
